# Generated by Django 3.2.3 on 2022-02-14 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='body_make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='second_name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='make',
            old_name='name_make',
            new_name='name',
        ),
        migrations.AddField(
            model_name='auto',
            name='comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auto',
            name='remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
