# Generated by Django 3.2.3 on 2022-02-25 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
