# Generated by Django 3.2.3 on 2022-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20220225_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
