# Generated by Django 3.2.3 on 2022-03-29 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20220329_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ad',
            new_name='ad_comment',
        ),
    ]
