# Generated by Django 3.2.3 on 2022-03-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_rename_ad_comment_ad_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-update_at',)},
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='commenting',
            new_name='comments',
        ),
    ]
