# Generated by Django 3.2.3 on 2022-03-29 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20220329_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
