# Generated by Django 3.2.3 on 2022-03-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_comment_ad_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ad_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad'),
        ),
    ]
