# Generated by Django 3.2.3 on 2022-04-01 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0014_rename_comments_ad_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='commented',
        ),
        migrations.AddField(
            model_name='ad',
            name='comment',
            field=models.ManyToManyField(related_name='Owned_comments', through='ads.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ad_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ads.ad'),
        ),
    ]
